// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.2
// source: deleteFromCart.proto

package deleteFromCart

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DeleteFromCart_Create_FullMethodName = "/DeleteFromCart/Create"
)

// DeleteFromCartClient is the client API for DeleteFromCart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeleteFromCartClient interface {
	Create(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type deleteFromCartClient struct {
	cc grpc.ClientConnInterface
}

func NewDeleteFromCartClient(cc grpc.ClientConnInterface) DeleteFromCartClient {
	return &deleteFromCartClient{cc}
}

func (c *deleteFromCartClient) Create(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, DeleteFromCart_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteFromCartServer is the server API for DeleteFromCart service.
// All implementations must embed UnimplementedDeleteFromCartServer
// for forward compatibility
type DeleteFromCartServer interface {
	Create(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedDeleteFromCartServer()
}

// UnimplementedDeleteFromCartServer must be embedded to have forward compatible implementations.
type UnimplementedDeleteFromCartServer struct {
}

func (UnimplementedDeleteFromCartServer) Create(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDeleteFromCartServer) mustEmbedUnimplementedDeleteFromCartServer() {}

// UnsafeDeleteFromCartServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeleteFromCartServer will
// result in compilation errors.
type UnsafeDeleteFromCartServer interface {
	mustEmbedUnimplementedDeleteFromCartServer()
}

func RegisterDeleteFromCartServer(s grpc.ServiceRegistrar, srv DeleteFromCartServer) {
	s.RegisterService(&DeleteFromCart_ServiceDesc, srv)
}

func _DeleteFromCart_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeleteFromCartServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeleteFromCart_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeleteFromCartServer).Create(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// DeleteFromCart_ServiceDesc is the grpc.ServiceDesc for DeleteFromCart service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeleteFromCart_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DeleteFromCart",
	HandlerType: (*DeleteFromCartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DeleteFromCart_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deleteFromCart.proto",
}
